class Attention(jit.ScriptModule):
    @jit.script_method
    def forward(self, attender, attendee, seq_length=None, mask=None):
        if mask is not None:
            ...
        if seq_length is not None:
            ...
        ...